name: MLGDamageIndicators
main: us.mlgfort.mlgdamageindicators.Main
description: Displays damage indicators in the form of holograms.
author: RoboMWM
version: 1.3.1
depend:
- HolographicDisplays
softdepend:
- Crackshot
loadbefore:
- DeathSpectating

commands:
  damageindicators:
    description: MLGDamageIndicators main command
    usage: /<command>
    aliases: [mlgdi, damageindicators, di]

permissions:
  damageindicators.reload:
    default: op